### ISSUE TITLE
Feature Request: Comments section

### ISSUE THREAD

**Issue by drakonizer** [icyphox/site#1]
Sometimes, after I read a post or two, I am overcome by the intense urge to comment. I am sure that I'm not alone. You could (read: should) make a comments section too. Sometimes, certain tit-bits of information from others might enhance your knowledge. 
If making one from scratch is hard, you could use a plug in, like disqus.

**Comment by icyphox** [comment]
Yeah, planned to use Disqus, but you see, I don't want another YouTube happening (I think I've mentioned this before)
