### ISSUE TITLE
Comment on IRC and PMs

### ISSUE THREAD

**Issue by mainettis** [icyphox/site#13]
Have up consider just using aliases or extensions/scripts to achieve your desired functionality in IRC? 

It just seems like setting up a channel for PM is a bit much. What if the channel is taken and you need to juggle multiple PMs?

If you want to maintain history you can log it and reload it via script.

**Comment by icyphox** [comment]
> It just seems like setting up a channel for PM is a bit much. What if
> the channel is taken and you need to juggle multiple PMs?

This setup is only between two people -- my brother and I. I am
unlikely to try this out with other people I talk to. The channel being
taken is a non-issue, it's just a name afterall. 

> If you want to maintain history you can log it and reload it via
> script.

History is already maintained via ZNC. The problem with using IRC's PM
feature is the chat buffer not persisting on the client across
sessions. This is an issue I face on both Weechat and Revolution IRC,
which is why we decided to give channels a shot, since they persist.


-- 
Anirudh Oppiliappan
0x8A93F96F78C5D4C4

**Comment by mainettis** [comment]
> This setup is only between two people -- my brother and I. I am
unlikely to try this out with other people I talk to.

If it works for what you need. That's great. I guess I got a bit thrown off by the use of PM/DM in your blog. What you're doing doesn't seem too different than starting a new channel/server in Discord.

> History is already maintained via ZNC. The problem with using IRC's PM
feature is the chat buffer not persisting on the client across
sessions.

Forgive me, I'm not familiar with ZNC.

I was suggesting that you could simulate persistence for PM/DMs. If you record your buffer's history in a location all your clients have access to. You could script some way to sync them. Have it open/maintain a buffer with a specific name/id depending on users you talk to. Maybe control how much of the chat history you want to keep on the buffer. The bonus behind this, is that you could probably use that same buffer to filter in all `\msg` and `\query` from a specific person (IRC filters are very handy). It could be a bit of a hack to get it to work with some free storage, should you need cross network use. Unless ZNC's history already lets you do that somehow. But, again, this may be more than you wanted/needed.

There is almost nothing you can't do with IRC client/servers. In the 90's I remember using it for VPNs and MUDs. I even used it as way to bring in all my IMs under one roof. ICQ, AIM, MSN, etc.. You could probably get twitter feeds and post via IRC. Though, there might not be a good reason to.

**Comment by icyphox** [comment]
> Unless ZNC's history already lets you do that somehow. But, again, this may be more than you wanted/needed.

Yes, ZNC's purpose is precisely what you described. It does all of that out-of-the-box. ( https://znc.in )

> There is almost nothing you can't do with IRC client/servers.

Indeed, it's the simplicity of the protocol that makes it so immensely flexible.

I don't know if this setup will last, but it does the job for now, without me having to use any non-free services -- that was my goal anyway.

**Comment by icyphox** [comment]
I'm going to go ahead and close this now, since I feel the discussion has halted. Feel free to reopen if you wish to do so.
