### ISSUE TITLE
FB50: Why can't the attacker be attacked, exactly?

### ISSUE THREAD

**Issue by pritambaral** [icyphox/site#3]
Referring to:

> The severity of this issue lies in the fact that the original owner completely loses access to their lock. They can't even "rebind" to get it back, since the current owner (the attacker) needs to authorize that.

You claim the victim cannot "rebind", because the attacker wouldn't authorize it. But if the attacker was able to "rebind" without the victim authorizing that, why can't the victim, in turn, do the same to the attacker after a takeover?

**Comment by icyphox** [comment]
> You claim the victim cannot "rebind"

The assumption is that the victim is unaware of the bug and is attempting a “rebind” via the app. 

But what you describe is entirely possible. In fact, any one of the 15k odd locks can be compromised remotely, ergo the attacker’s as well.

**Comment by pritambaral** [comment]
I see. The assumption wasn't obvious to me. It seemed instead like a rebind somehow added a lock that wasn't there before.
